version: "3.8"
services:
  # Spring Boot backend service (MySQL connected)
  spring-app:
    image: keeleybootcamp/spring-app  
    build:
      context: ./  
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/mydb  
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=mysecretpassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update  
    ports:
      - "8000:8000"  
    depends_on:
      - mysql-db
    networks:
      - app-network

  # React frontend service
  react-app:
    image: keeleybootcamp/react-app  
    build:
      context: ./
    ports:
      - "80:80" 
    networks:
      - app-network


  # MySQL database service
  mysql-db:
    image: mysql:5.7 
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword  
      MYSQL_DATABASE: mydb  
    volumes:
      - mysql-data:/var/lib/mysql  
    ports:
      - "3306:3306"  
    networks:
      - app-network

volumes:
  mysql-data:  # add volume details

networks:
  app-network:
    driver: bridge
