version: "3.8"
services:
  # Spring Boot backend service (MySQL connected)
  spring-app:
    image: keeleybootcamp/spring-app  # Replace with your actual image name or build context
    build:
      context: ./  # Path to the Spring Boot app directory
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/mydb  # Configure MySQL URL
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=mysecretpassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update  # Configure JPA
    ports:
      - "8000:8000"  # Exposing the backend on port 8080
    depends_on:
      - mysql-db
    networks:
      - app-network

  # React frontend service (First frontend)
  react-app:
    image: keeleybootcamp/react-app  # Replace with your actual image or build context
    build:
      context: ./  # Path to the first React app
    ports:
      - "80:80"  # Exposing React frontend on port 3000 (or adjust as needed)
    networks:
      - app-network


  # MySQL database service
  mysql-db:
    image: mysql:5.7  # Use MySQL 5.7 or another version as needed
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword  # Set MySQL root password
      MYSQL_DATABASE: mydb  # Database name to be created
    volumes:
      - mysql-data:/var/lib/mysql  # Volume to persist data
    ports:
      - "3306:3306"  # Exposing MySQL on port 3306
    networks:
      - app-network

volumes:
  mysql-data:  # Define the volume to persist MySQL data

networks:
  app-network:
    driver: bridge
